Repository eorzea-weather/node-eorzea-weather, pull requests merged in 2020-07, with the labels that each got.

#201 Add Wolves' Den Pier
  src/EorzeaWeather.js
  src/chances.js
  src/locales/en.json
  src/locales/ja.json
  src/zones.js
Labels: enhancement

#202 Change organization
  README.md
Labels: enhancement

#210 Ran `yarn upgrade`
  yarn.lock
Labels: dependencies

#211 Introduce GitHub Actions
  .github/workflows/test.yml
Labels: enhancement

#212 Disable CircleCI
  .circleci/config.yml
Labels: enhancement

#203 Replace to TypeScript
  .babelrc.js
  .eslintignore
  .eslintrc.js
  .gitignore
  .npmignore
  package.json
  rollup.config.js
  src/EorzeaWeather.js
  src/EorzeaWeather.ts
  src/__tests__/EorzeaWeather.ts
  src/chances.ts
  src/index.js
  src/index.ts
  src/locales/en.ts
  src/locales/index.js
  src/locales/index.ts
  src/locales/ja.ts
  src/utils/calculateForecastTarget.ts
  src/weathers.ts
  src/zones.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#214 Add files prop to pkg
  package.json
Labels: bug

#215 Introduce Prettier
  package.json
  src/EorzeaWeather.ts
  src/index.ts
  src/locales/en.ts
  src/locales/ja.ts
  src/utils/calculateForecastTarget.ts
  yarn.lock
Labels: enhancement

#216 Ran `yarn upgrade`
  package.json
  yarn.lock
Labels: dependencies

#219 Add typing files
  package.json
Labels: bug
